## ~/.bashrc aliases

alias ll='ls -la'
alias gs='git status'

alias c='clear'
alias h='history'

##30 okay alias
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias home='cd ~'
alias docs='cd ~/Documents'
alias dls='cd ~/Downloads'
alias desk='cd ~/Desktop'
alias music='cd ~/Music'
alias pics='cd ~/Pictures'
alias vids='cd ~/Videos'
alias www='cd /var/www'
alias src='cd /usr/src'
alias etc='cd /etc'
alias up='sudo apt update && sudo apt upgrade'
alias inst='sudo apt install'
alias rem='sudo apt remove'
alias search='apt search'
alias clear='clear'
alias e='exit'
alias psg='ps aux | grep'
alias mkdir='mkdir -pv'
alias rmdir='rmdir -v'
alias cp='cp -v'
alias mv='mv -v'
alias rm='rm -v'
alias df='df -h'
alias du='du -h'
